### ISSUE TITLE
Weird SIGSEGV when calling pvrecorder from diffrent processes

### ISSUE THREAD

**Issue by ppoffice** [Picovoice/pvrecorder#24]
## Runtime Information

```
$ lsb_release -idrc
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

$ uname -a
Linux ubuntu 5.13.0-19-generic #19-Ubuntu SMP Thu Oct 7 21:58:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ go version
go version go1.17.8 linux/amd64

$ ls ~/go/pkg/mod/github.com/\!picovoice/pvrecorder/sdk/
go@v1.0.2
```

## Step to reproduce

1. Create two test files `test1.go` and `test2.go`:

    ```go
    // test1.go
    package main
    
    import (
	    "log"
	    "time"
    
	    pvrecorder "github.com/Picovoice/pvrecorder/sdk/go"
    )
    
    func main() {
	    time.Sleep(5 * time.Second)
    
	    recorder := pvrecorder.PvRecorder{
		    DeviceIndex:    -1,
		    FrameLength:    512,
		    BufferSizeMSec: 1000,
		    LogOverflow:    0,
	    }
	    if err := recorder.Init(); err != nil {
		    log.Fatal(err)
	    }
	    recorder.Delete()
    }
    ```

    ```go
    // test2.go
    package main
    
    import (
	    "fmt"
    
	    pvrecorder "github.com/Picovoice/pvrecorder/sdk/go"
    )
    
    func main() {
	    fmt.Println(pvrecorder.GetAudioDevices())
    }
    ```

2. Open two terminal windows `term1` and `term2`, run `test1.go` in `term1` and then run `test2.go` in `term2` immediately:

    ```shell
    # term1
    go run test1.go
    ```
    
    ```shell
    # term2
    go run test2.go
    ```

3. Five seconds later, `test1.go` will exit with `SIGSEGV: segmentation violation`:

    ```
    fatal error: unexpected signal during runtime execution
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x2180 pc=0x2180]
    
    runtime stack:
    runtime.throw({0x4c7944, 0x436b95})
            /usr/local/go/src/runtime/panic.go:1198 +0x71
    runtime.sigpanic()
            /usr/local/go/src/runtime/signal_unix.go:719 +0x396
    
    goroutine 1 [syscall]:
    runtime.cgocall(0x4a3b00, 0xc00005de20)
            /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00005ddf8 sp=0xc00005ddc0 pc=0x4051fc
    github.com/Picovoice/pvrecorder/sdk/go._Cfunc_pv_recorder_init_wrapper(0x7f0f300b4010, 0xffffffff, 0x200, 0x3e8, 0x0, 0xc000010078)
            _cgo_gotypes.go:191 +0x4c fp=0xc00005de20 sp=0xc00005ddf8 pc=0x4a240c
    github.com/Picovoice/pvrecorder/sdk/go.nativePvRecorderType.nativeInit.func1(0xffffffffffffffff, 0x200, 0x3e8, 0x0, 0xc00005deb0)
            /home/ubuntu/go/pkg/mod/github.com/!picovoice/pvrecorder/sdk/go@v1.0.2/pvrecorder_posix.go:112 +0xd1 fp=0xc00005de68 sp=0xc00005de20 pc=0x4a2e71
    github.com/Picovoice/pvrecorder/sdk/go.nativePvRecorderType.nativeInit({}, 0xc00005df38)
            /home/ubuntu/go/pkg/mod/github.com/!picovoice/pvrecorder/sdk/go@v1.0.2/pvrecorder_posix.go:112 +0x8a fp=0xc00005ded8 sp=0xc00005de68 pc=0x4a2d4a
    github.com/Picovoice/pvrecorder/sdk/go.(*PvRecorder).Init(0x12a05f200)
            /home/ubuntu/go/pkg/mod/github.com/!picovoice/pvrecorder/sdk/go@v1.0.2/pvrecorder.go:121 +0x19 fp=0xc00005df20 sp=0xc00005ded8 pc=0x4a2779
    main.main()
            /home/ubuntu/test1.go:19 +0x67 fp=0xc00005df80 sp=0xc00005df20 pc=0x4a3847
    runtime.main()
            /usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc00005dfe0 sp=0xc00005df80 pc=0x435427
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x460361
    exit status 2
    ```

4. Run `test1.go` alone will cause SIGSEGV.

## Possible Cause

Is `pvrecorder` trying to allocate or access anything in the shared memory?

## Related Issues

- https://github.com/Picovoice/rhino/issues/325
- https://github.com/Picovoice/porcupine/issues/683

**Comment by ErisMik** [comment]
Thank you for the report and your detailed reproduction instructions. We were able to reproduce the issue, and are currently investigating the cause.
