### ISSUE TITLE
Python: RuntimeError when importing pvrecorder on windows 10 (amd64)

### ISSUE THREAD

**Issue by vincent-heng** [Picovoice/pvrecorder#55]
Hi,

I got pvrecorder 1.1.1 installed via pip3.
Windows 10, amd64

My script is extremely simple:
`import pvrecorder`

When I run it with `py test_pv.py`, I got the following stacktrace:
```py
Traceback (most recent call last):
  File "test_pv.py", line 1, in <module>
    import pvrecorder
  File "C:\Users\Vincent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pvrecorder\__init__.py", line 12, in <module>
    from .pvrecorder import PvRecorder
  File "C:\Users\Vincent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pvrecorder\pvrecorder.py", line 20, in <module>
    class PvRecorder(object):
  File "C:\Users\Vincent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pvrecorder\pvrecorder.py", line 203, in PvRecorder
    _LIBRARY = cdll.LoadLibrary(_lib_path.__func__())
  File "C:\Users\Vincent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pvrecorder\pvrecorder.py", line 191, in _lib_path
    raise RuntimeError("Current system is not supported.")
RuntimeError: Current system is not supported.
```

Note: I didn't installed the following requirements from the README.md file as I think it's only needed to compile pvrecorder?

- CMake 3.4+.
- C99 compatible compiler.
- Windows: MinGW.

Did I miss something?

**Comment by vincent-heng** [comment]
Hello, thanks for your quick answer!

```
> CMD /C .\platform.bat
windows amd64
> echo %ERRORLEVEL%
%ERRORLEVEL%
```

**Comment by vincent-heng** [comment]
I ran it through powershell.
Here's the result from cmd:

```
> CMD /C platform.bat
windows amd64
> echo %ERRORLEVEL%
0
```

**Comment by vincent-heng** [comment]
That's it! Thanks for your help!
