### ISSUE TITLE
Segmentation violation error in go sdk

### ISSUE THREAD

**Issue by dedalusj** [Picovoice/pvrecorder#65]
I'm probably missing something basic but I get the stack trace below when I clone the repo on Raspberry Pi 4 and try to run the demo with `go run demo/demo.go` from the `sdk/go` folder.

### Stack trace
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0xfc9eb, 0x2a})
	/usr/local/go/src/runtime/panic.go:1047 +0x4c fp=0xffaf88a8 sp=0xffaf8894 pc=0x49cd4
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x29c fp=0xffaf88c4 sp=0xffaf88a8 pc=0x63084

goroutine 1 [syscall]:
runtime.cgocall(0xdb700, 0x143aee4)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0x143aecc sp=0x143aeb4 pc=0x1485c
github.com/Picovoice/pvrecorder/sdk/go._Cfunc_pv_recorder_version_wrapper(0x0)
	_cgo_gotypes.go:265 +0x34 fp=0x143aee0 sp=0x143aecc pc=0xd816c
github.com/Picovoice/pvrecorder/sdk/go.nativePvRecorderType.nativeVersion.func1()
	/home/user/pvrecorder/sdk/go/pvrecorder_native.go:205 +0x48 fp=0x143aef8 sp=0x143aee0 pc=0xda138
github.com/Picovoice/pvrecorder/sdk/go.nativePvRecorderType.nativeVersion({})
	/home/user/pvrecorder/sdk/go/pvrecorder_native.go:205 +0x14 fp=0x143af08 sp=0x143aef8 pc=0xda0c8
github.com/Picovoice/pvrecorder/sdk/go.Version(...)
	/home/user/pvrecorder/sdk/go/pvrecorder.go:205
main.main()
	/home/user/pvrecorder/sdk/go/demo/demo.go:31 +0x158 fp=0x143afc0 sp=0x143af08 pc=0xda534
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x268 fp=0x143afec sp=0x143afc0 pc=0x4c980
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x143afec sp=0x143afec pc=0x7d1dc
```

### Info

```
$ go env
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/pvrecorder/sdk/go/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1854822513=/tmp/go-build -gno-record-gcc-switches"
```

```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by ksyeo1010** [comment]
We couldn't reproduce the issue on our end so we will need more information.
1. What is your gcc version (`gcc --version`)?
2. What is your glibc version (`ldd --version`)?
3. Are you in 32bit or 64bit rpi (`uname -m`)?

**Comment by dedalusj** [comment]
```
$ gcc --version
gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ ldd --version
ldd (Debian GLIBC 2.31-13+rpt2+rpi1+deb11u5) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

```
$ uname -m
aarch64
```

**Comment by ksyeo1010** [comment]
we just released a new version, can you try again and see if it works? I don't have any issues running on the same configurations you posted above.

**Comment by dedalusj** [comment]
Yeah tried the new version and it is working. Thanks
