### ISSUE TITLE
PvRecorder throws error when run in systemd service

### ISSUE THREAD

**Issue by c-iot-admin** [Picovoice/pvrecorder#87]
I am having the exact same issue as described in https://askubuntu.com/questions/1469812/pvrecorder-throws-error-when-run-in-systemd-service, so I figured I would cross-post it here. I am using a Raspberry Pi 3 running on:
```
$lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
The systemd logs are:
```
02-10-2023 16:29:03 - INFO - Porcupine version: 2.2.0
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM dsnoop
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM dsnoop:0
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM dsnoop:0,0
/home/pi/demo/venv/lib/python3.9/site-packages/pvrecorder/lib/raspberry-pi/cortex-a53/libpv_recorder.so
Traceback (most recent call last):
  File "/home/pi/demo/test.py", line 4, in <module>
    recorder = PvRecorder(device_index=-1, frame_length=512)
  File "/home/pi/demo/venv/lib/python3.9/site-packages/pvrecorder/_pvrecorder.py", line 113, in __init__
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to initialize PvRecorder.")
RuntimeError: Failed to initialize PvRecorder.
```
When I run it as a normal user `pi`, it works perfectly.

My goal here is to make the script run at boot, but I am failing to do this with systemd.

**Comment by kenarsa** [comment]
take a look at [this](https://github.com/Picovoice/pvrecorder/issues/46)

**Comment by c-iot-admin** [comment]
Thanks, somehow I missed that.

> take a look at [this](https://github.com/Picovoice/pvrecorder/issues/46)
