### ISSUE TITLE
electron 中使用@picovoice/pvrecorder-node  报错

### ISSUE THREAD

**Issue by gpq456** [Picovoice/pvrecorder#91]
A dynamic link library (DLL) initialization routine failed.
\\?\D:\worker\Fay\live2d-pixi\node_modules\@picovoice\pvrecorder-node\lib\windows\amd64\pv_recorder.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1869)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at <static_initializer> (D:\worker\Fay\live2d-pixi\node_modules\@picovoice\pvrecorder-node\dist\pv_recorder.js:23:26)
    at Object.<anonymous> (D:\worker\Fay\live2d-pixi\node_modules\@picovoice\pvrecorder-node\dist\pv_recorder.js:17:18)

**Comment by ksyeo1010** [comment]
Can't help with whats wrong with only this information. Can you try out the official node.js demo and see if that is causing an issue?

**Comment by klAvAx** [comment]
I am Getting the same error on Windows:
`Error: A dynamic link library (DLL) initialization routine failed.
\\?\F:\Projects\micrec\node_modules\@picovoice\pvrecorder-node\lib\windows\amd64\pv_recorder.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at <static_initializer> (F:\Projects\micrec\node_modules\@picovoice\pvrecorder-node\dist\pv_recorder.js:23:26)
    at Object.<anonymous> (F:\Projects\micrec\node_modules\@picovoice\pvrecorder-node\dist\pv_recorder.js:17:18)
`
Additional info which might help
Windows 10 22H2; Node v20.11.1;
only major difference i can think of is i am using ESM (`import { PvRecorder } from '@picovoice/pvrecorder-node';`) instead of CJS (`const { PvRecorder } = require("@picovoice/pvrecorder-node");`)

Official demo installed globaly does work fine on windows

Interestingly everything works fine on MacOS in dev environment

**Comment by glk-hll** [comment]
@ksyeo1010 @gpq456 I have encountered the same problem, some restrictions that prevent me from using the Voice Processor Web SDK on the web, but I still don't know how to use PvRecorder in Electron .  #76

**Comment by albho** [comment]
We currently don't support Electron for Windows, but it's on our roadmap for future implementation. I'll update this thread once it's available.

**Comment by albho** [comment]
Thanks everyone for waiting, this has now been fixed. #105
