### ISSUE TITLE
not compatible problem wit Raspberry PI5

### ISSUE THREAD

**Issue by joerk1960** [Picovoice/pvrecorder#93]
pv_recorder_demo --show_audio_devices
Traceback (most recent call last):
  File "/home/joerk/.local/bin/pv_recorder_demo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/joerk/.local/lib/python3.11/site-packages/pvrecorderdemo/pv_recorder_demo.py", line 42, in main
    devices = PvRecorder.get_available_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerk/.local/lib/python3.11/site-packages/pvrecorder/_pvrecorder.py", line 231, in get_available_devices
    get_available_devices_func = PvRecorder._get_library().pv_recorder_get_available_devices
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerk/.local/lib/python3.11/site-packages/pvrecorder/_pvrecorder.py", line 261, in _get_library
    cls._relative_library_path = default_library_path()
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerk/.local/lib/python3.11/site-packages/pvrecorder/_pvrecorder.py", line 33, in default_library_path
    raise RuntimeError("Current system is not supported.")
RuntimeError: Current system is not supported.

**Comment by joerk1960** [comment]
Found a workaroud:
def _pv_linux_machine(machine):
...
side-packages/pvporcupine/_utli.py: 


      return 'cortex-a57' + arch_info
    elif '0xd08' == cpu_part:
        return 'cortex-a72' + arch_info
    elif '0xc08' == cpu_part:
        return 'beaglebone' + arch_info
    elif machine == 'armv7l':
        log.warning(
            'WARNING: Please be advised that this device (CPU part = %s) is not officially supported by Picovoice. '
            'Falling back to the armv6-based (Raspberry Pi Zero) library. This is not tested nor optimal.' % cpu_part)
        return 'arm11'
    # Added lines for Raspberry Pi 5 support
    elif '0xd0b' == cpu_part:
       return 'cortex-a72' + arch_info
    else:
        raise NotImplementedError("Unsupported CPU: '%s'." % cpu_part)
...

and side-packages/pvrecorder/resources/scripts/platform.sh
case $kernel in
       case $cpu_part in
            "0xb76") kernel="raspberry-pi" arch="arm11"$arch_info;;
            "0xc07") kernel="raspberry-pi" arch="cortex-a7"$arch_info ;;
            "0xd03") kernel="raspberry-pi" arch="cortex-a53"$arch_info ;;
            "0xd07") kernel="jetson" arch="cortex-a57"$arch_info ;;
            "0xd08") kernel="raspberry-pi" arch="cortex-a72"$arch_info ;;
            "0xc08") kernel="beaglebone" arch=$arch_info ;;
            # Added lines for Raspberry Pi 5 support
            "0xd0b" ) kernel="raspberry-pi" arch="cortex-a72"$arch_info ;;
            *) exit 1;;

....

**Comment by mrrostam** [comment]
Official support for Raspberry Pi 5 is on our roadmap, but I cannot provide a specific timeframe at the moment.
